# .cnb.yml

# 匹配以 develop 开头的分支名
develop*:
  ## 推送触发
  push:
    - services:
        - docker
      runner:
        tags: cnb:arch:amd64
        cpus: 64
      imports:
        - https://cnb.cool/xwsir/dinphy/env/-/blob/main/moments.yml
      stages:
        - name: 登录Docker仓库
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: 获取dev版本号
          script: echo -n $(date +%s)
          exports:
            info: DEV_VERSION
        - name: 编译Docker dev镜像
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:dev-$DEV_VERSION .
        - name: 推送Docker镜像到CNB
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:dev-$DEV_VERSION  
# 构建以 main 开头的分支
main*:
  web_trigger_main:
    - services:
        - docker
      runner:
        tags: cnb:arch:amd64
        cpus: 64
      imports:
        - https://cnb.cool/xwsir/dinphy/env/-/blob/main/moments.yml
      stages:
        - name: 登录Docker仓库
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: 编译Docker latest镜像
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
        - name: 推送Docker镜像到CNB
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
